name: Heroku Deploy

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}      
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
      

      - name: Cache Dependencies
        run: deno cache deps.ts

      - name: Run Tests
        run: deno test -A --unstable
